### ISSUE TITLE
To large error 

### ISSUE THREAD

**Issue by kermit943** [puuu/USIWire#1]
Hy 
I tried to compile Example Mastercode and a Arduino stock wire example with "#include <USIWire.h>" for Attiny2313 always get the error code is to big.

Am I doing something wrong?

Error 

<Sketch uses 2518 bytes (122%) of program storage space. Maximum is 2048 bytes.

Global variables use 200 bytes (156%) of dynamic memory, leaving -72 bytes for local variables. Maximum is 128 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board ATtiny2313/4313.
>

Thanks for help.

**Comment by puuu** [comment]
Hi, thank you for using USIWire!

I am a little bit afraid because your sketches seems to big for the Attiny2313.

Here are some hints.
- You can enable the link time optimization (LTO) in the ATTinyCore
(Arduino Tools menu) that will decrease the size a little.
- Avoid using the Serial module...

Then I can compile the examples:

master_writer:
```
Sketch uses 1366 bytes (66%) of program storage space. Maximum is 2048
bytes.
Global variables use 61 bytes (47%) of dynamic memory, leaving 67 bytes
for local variables. Maximum is 128 bytes.
```

slave_sender:
```
Sketch uses 1042 bytes (50%) of program storage space. Maximum is 2048
bytes.
Global variables use 59 bytes (46%) of dynamic memory, leaving 69 bytes
for local variables. Maximum is 128 bytes.
```

TestSlave:
```
Sketch uses 2036 bytes (99%) of program storage space. Maximum is 2048
bytes.
Global variables use 110 bytes (85%) of dynamic memory, leaving 18 bytes
for local variables. Maximum is 128 bytes.
Low memory available, stability problems may occur.
```

`slave_receiver` and `master_reader` are to big because of the Serial
module. By removing all lines with `Serial.` they can compile:

slave_receiver (disable Serial):
```
Sketch uses 1030 bytes (50%) of program storage space. Maximum is 2048
bytes.
Global variables use 51 bytes (39%) of dynamic memory, leaving 77 bytes
for local variables. Maximum is 128 bytes.
```

master_reader (disable Serial):
```
Sketch uses 1306 bytes (63%) of program storage space. Maximum is 2048
bytes.
Global variables use 54 bytes (42%) of dynamic memory, leaving 74 bytes
for local variables. Maximum is 128 bytes.
```

If you require `Serial`, you may be better with an Attiny4313.
